### PR TITLE
Added iOS support

### PR DESCRIPTION
**Pull request by geo242**

### CODE REVIEW

**Comment by Jaspur** [comment]
@InteractiveObject @geo242  it doesn't work by iOS without this PR?

**Comment by younes200** [comment]
Hi @Jaspur no iOs is implemented by @geo242 in his PR, fill free to test the PR instead and I'll make the merge ;)

**Comment by Jaspur** [comment]
it does. @geo242 should fix the merge conflict first I guess before merge? ;)

**Comment by geo242** [comment]
@younes200 @Jaspur  - I will try to get it all fixed up this weekend so you can merge it. Thanks!

**Comment by Jaspur** [comment]
@geo242 great!

**Comment by geo242** [comment]
@Jaspur @younes200 I have merged in the latest to the iOS branch and there shouldn't be any issues with merging it into master. Let me know if there are. Thanks!

**Comment by Jaspur** [comment]
@geo242 tried the demo-app, doesn't work?

**Comment by Jaspur** [comment]
@geo242 some errors still with references? https://www.dropbox.com/s/llrsuobizib1ri3/Schermafdruk%202016-02-24%2013.48.47.png?dl=0 
StarIO framework is added to the repo according the docs of them.

**Pull request merged**
